### ISSUE TITLE
Design hifi registration page, sign in page and user authentication

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#2]

**Comment by diessen** [comment]
Done.
[Figma link](https://www.figma.com/file/JcRRSWP3gYKq1Zz6jzSwlL?node-id=0:1)
 [Asset folder link](https://drive.google.com/drive/folders/1-3057KGjpuWBAyFcdgDSafIvRx3mKZh2)

**Comment by ChiamakaEzeoke** [comment]
Thank you. Great job!
