### ISSUE TITLE
UX write up and proof reading of all webpages

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#3]

**Comment by Ellarey** [comment]
Write up done, proofreading also done.
Just waiting to cross check and make final adjustments

**Comment by ChiamakaEzeoke** [comment]
Well done

**Comment by Ellarey** [comment]
https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1046%3A3066

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1107%3A3344

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=763%3A2093

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=959%3A3705

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=411%3A2
