### ISSUE TITLE
Design documentation & blog page

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#32]

**Comment by TessyCN** [comment]
I'm done with it

**Comment by TessyCN** [comment]
[Blog, single article, and documentation pages](https://www.figma.com/file/AqHjdqBc5JNbuCMxZ9R1dR/Blog-and-documentation-pages?node-id=0%3A1)

**Comment by TessyCN** [comment]
**Desktop View**
[Documentation Page HiFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1954%3A9451)
[Blog page HiFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1046%3A3066)
[Single Article page HiFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1107%3A3344)
[Blog page LowFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=605%3A849)
[Single Article page LowFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=2036%3A10173)


**Tablet View**
[Blog page LowFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=607%3A849)
[Single Article page LowFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=609%3A918)

**Mobile View**
[Blog page LowFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=605%3A977)
[Single Article page LowFi](https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=605%3A1054)
