### ISSUE TITLE
implement deployment/production

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#34]

**Comment by 4dbyron** [comment]
Upon The Changes /Pull Request #65 Being Accepted,
I Will Update The ReadMe Accordingly,
And Make The Heroku Version Auto-Update Straight From Main Repo, instead of My Fork.
🙏️

Live App Now On:
https://iconcity.herokuapp.com/

**Comment by Engr-Zeus** [comment]
What about the database? is it still on the Django sqlite?
