### ISSUE TITLE
Code the emptycollections page

### ISSUE THREAD

**Issue by youngancient** [zuri-training/favicon-gen-team-70#37]

**Comment by Jemvaris** [comment]
Added emptycollection.html page to templates/dashboard
emptycollection.css in static/dashboard and
noCollection.png image, in static/assets/dashboard
Added a create icon button which links back to the home sign in page!

https://jemvaris.github.io/favicon-gen-team-70-frontend/dashboard/emptyCollections.html

**Comment by ChiamakaEzeoke** [comment]
Well done!
