### ISSUE TITLE
Design hifi for upload page

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#5]

**Comment by Adeagbo00** [comment]
Worked and designed these pages
https://www.figma.com/file/byfPUZ08ToFg1KILCMlcxq/Team-70-Team-work?node-id=0%3A1

**Comment by Adeagbo00** [comment]
Worked and designed these pages
https://www.figma.com/file/byfPUZ08ToFg1KILCMlcxq/Team-70-Team-work?node-id=0%3A1

**Comment by ChiamakaEzeoke** [comment]
Nice!
