### ISSUE TITLE
Prototyping of all web pages

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#6]

**Comment by Tiene-Abasi** [comment]
Prototype for web has been done

**Comment by ChiamakaEzeoke** [comment]
Nice!

**Comment by DeleyeDedayo** [comment]
Prototyping done!

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1011%3A3041

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=1861%3A6511

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=953%3A5323

https://www.figma.com/file/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=953%3A3054

**Comment by Tiene-Abasi** [comment]
[Link to Prototype](https://www.figma.com/proto/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=953%3A4148&scaling=min-zoom&page-id=411%3A2&starting-point-node-id=953%3A4148)

**Comment by Ellarey** [comment]
Done!
https://www.figma.com/proto/wrHY0CRIvSYpyKUrfm8Wx9/Team_70-team-library?node-id=953%3A4148&scaling=min-zoom&page-id=411%3A2&starting-point-node-id=953%3A4148
