### ISSUE TITLE
Quality Assurance

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#71]

**Comment by Abeeujah** [comment]
https://docs.google.com/document/d/19tmgVYrS3Ffhw7XQJNNvw0cJCeGwFiNt_a1lCFZcVrc/edit?usp=sharing

**Comment by ChiamakaEzeoke** [comment]
Comments from the supervisors need to be added to t his doc. Grant me access so I can add them.

**Comment by ChiamakaEzeoke** [comment]
All the bugs will be shared tonight
