### ISSUE TITLE
Implement sign up and sign in page

### ISSUE THREAD

**Issue by ChiamakaEzeoke** [zuri-training/favicon-gen-team-70#9]

**Comment by ChiamakaEzeoke** [comment]
Great work on the sign up page. Please kindly add a button titled Home just like the Sign Up button that will lead to the Landing Page just at the top right.

**Comment by ChiamakaEzeoke** [comment]
kindly put your hosted link here so that can close your issue

**Comment by stephanie951** [comment]
https://stephanie951.github.io/favicon-frontend/

**Comment by ChiamakaEzeoke** [comment]
Thank you and great work!
